item{
  id:1
  name:"good"
}
item {
    id: 2
    name: 'manipulated_front'
}
item {
    id: 3
    name: 'scratch_head'
}
item {
    id: 4
    name: 'scratch_neck'
}
item {
    id: 5
    name: 'thread_side'
}
item {
    id: 6
    name: 'thread_top'
}